### ISSUE TITLE
help

### ISSUE THREAD

**Issue by moosje2003** [Yentis/emotereplacer-gifutils#10]
where do i paste the code in the EmoteReplacer.plugin.js 
all i get is a long string of text

[gif-utils.js.txt](https://github.com/Yentis/emotereplacer-gifutils/files/10133689/gif-utils.js.txt)

**Comment by Yentis** [comment]
This repository is obsolete, the code is now already included in the source code of https://github.com/Yentis/betterdiscord-emotereplacer/tree/master/src
